version: '3.3'

services:
  web:
    build: ./web/
    restart: on-failure
    networks:
      internal:
        aliases:
          - python
    depends_on:
      - redis

  nginx:
    image: nginx
    networks:
      - internal
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certif:/certif
    depends_on:
      - web
      - redis
    ports:
      - "443:443"

  redis:
    image: redis
    networks:
      internal:
        aliases:
          - db
    expose:
      - "6379"

networks:
  internal:
